//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public string ProjectId { get; set; }
        public int iati_activityID { get; set; }
        public Nullable<System.DateTime> LastUpdateDateTime { get; set; }
        public string IatiIdentifier { get; set; }
        public string JournalNo { get; set; }
        public string LevelNo { get; set; }
        public string Title { get; set; }
        public string ActivityStatus { get; set; }
        public string ContactInfoEmail { get; set; }
        public string ContactInfoOrganisation { get; set; }
        public string ContactInfoPerson { get; set; }
        public string ContactInfoTelephone { get; set; }
        public string Description { get; set; }
    }
}
