//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Nullable<System.DateTime> LastUpdateDateTime { get; set; }
        public string ActivityID { get; set; }
        public string IATIIdentifier { get; set; }
        public string JournalNo { get; set; }
        public string Title { get; set; }
        public string ActivityStatus { get; set; }
        public Nullable<System.DateTime> DateStartPlanned { get; set; }
        public Nullable<System.DateTime> DateEndPlanned { get; set; }
        public Nullable<System.DateTime> DateStartActual { get; set; }
        public Nullable<System.DateTime> DateEndActual { get; set; }
        public string ContactInfoEmail { get; set; }
        public string ContactInfoOrganisation { get; set; }
        public string ContactInfoPerson { get; set; }
        public string ContactInfoTelephone { get; set; }
        public string Description { get; set; }
        public string IATIIdentifierProject { get; set; }
        public string ActivityIDProject { get; set; }
    }
}
