//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Budget
    {
        public int budgetID { get; set; }
        public string ActivityID { get; set; }
        public string CurrencyCode { get; set; }
        public System.DateTime BudgetDate { get; set; }
        public long BudgetAmount { get; set; }
        public string CountryCode { get; set; }
        public string CountryCodeIati { get; set; }
        public string OrganisationId { get; set; }
        public Nullable<int> SectorCode { get; set; }
        public string SubcompanyCode { get; set; }
        public Nullable<int> RegionCode { get; set; }
        public string RegionName { get; set; }
        public string CountryName { get; set; }
        public string OrganisationName { get; set; }
        public string SectorName { get; set; }
        public string BudgetSubSection { get; set; }
    }
}
