//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aidtype
    {
        public int ID { get; set; }
        public string aidtype_code { get; set; }
        public string aidtype_name_uk { get; set; }
        public string parent_code { get; set; }
        public string parent_name_uk { get; set; }
        public string aidtype_name_dk { get; set; }
        public string parent_name_dk { get; set; }
    }
}
