//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelStructure
    {
        public string Date { get; set; }
        public Nullable<double> C2013 { get; set; }
        public string F3 { get; set; }
        public long ID { get; set; }
    }
}
