//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelTable
    {
        public Nullable<double> DWID_Channel { get; set; }
        public string Name { get; set; }
        public string Organisation_Code { get; set; }
        public Nullable<double> DWID_Parent { get; set; }
        public string Kolonne1 { get; set; }
        public string F6 { get; set; }
        public string Kobling_fra_datagrundlag__Channelcode_i_2012__drøftes_færdig_for { get; set; }
        public long ID { get; set; }
    }
}
