//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public string country_code { get; set; }
        public string name_uk { get; set; }
        public string name_dk { get; set; }
        public string parent_code { get; set; }
        public string country_code_iati { get; set; }
        public Nullable<int> Code { get; set; }
        public string Countrytype { get; set; }
        public string partner_country_yn { get; set; }
    }
}
