//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ID { get; set; }
        public Nullable<int> dwid_country { get; set; }
        public string country_code { get; set; }
        public string country1 { get; set; }
        public string name_danish { get; set; }
        public string parent_code { get; set; }
        public Nullable<double> code { get; set; }
        public Nullable<double> iso_code { get; set; }
        public Nullable<double> dwid_parent { get; set; }
    }
}
