//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DacTable
    {
        public Nullable<double> dwid_purpose { get; set; }
        public Nullable<double> DAC_CODE { get; set; }
        public string DAC_TXT_UK { get; set; }
        public string PURPOSE { get; set; }
        public Nullable<double> PURPOSE_CODE { get; set; }
        public string DAC_Code_Parent { get; set; }
        public string Dac_Code_Text_Parent { get; set; }
        public string F8 { get; set; }
        public string Kobling_fra_datagrundlag__Purpose_Code__Zoomet_ind_på_et_overbyg { get; set; }
        public long ID { get; set; }
    }
}
