//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IatiDbEntities : DbContext
    {
        public IatiDbEntities()
            : base("name=IatiDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChannelStructure> ChannelStructures { get; set; }
        public virtual DbSet<ChannelTable> ChannelTables { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DacTable> DacTables { get; set; }
        public virtual DbSet<Modality> Modalities { get; set; }
    
        public virtual ObjectResult<Activities_Result> GetActivitiesXml(string recipientCountry)
        {
            var recipientCountryParameter = recipientCountry != null ?
                new ObjectParameter("RecipientCountry", recipientCountry) :
                new ObjectParameter("RecipientCountry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Activities_Result>("GetActivitiesXml", recipientCountryParameter);
        }
    }
}
