//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finanslov
    {
        public int ID { get; set; }
        public Nullable<int> SubCompanyCode { get; set; }
        public string BudgetSubSection { get; set; }
        public string BudgetSubSection_Name_UK { get; set; }
        public string BudgetSubSection_Name_DK { get; set; }
        public string BudgetSection { get; set; }
        public string BudgetSection_Name_DK { get; set; }
        public string BudgetSection_Name_UK { get; set; }
        public string BudgetGroup { get; set; }
        public string BudgetGroup_Name_UK { get; set; }
        public string BudgetGroup_Name_DK { get; set; }
        public string Category1_DK { get; set; }
        public string Category1_UK { get; set; }
        public string Category2_DK { get; set; }
        public string Category2_UK { get; set; }
    }
}
