//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modality
    {
        public string MODALITY_ID { get; set; }
        public string MODALITY_PARENT_ID { get; set; }
        public string MODALITY_TYPE { get; set; }
        public string MODALITY_SUBTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CLARIFICATION { get; set; }
        public long ID { get; set; }
    }
}
