//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Um.DataServices.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisation
    {
        public int ID { get; set; }
        public Nullable<int> organisation_code { get; set; }
        public string organisation_name_uk { get; set; }
        public string organisation_name_dk { get; set; }
    }
}
